# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 615)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/windows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.YH_Box = QtWidgets.QComboBox(self.widget_3)
        self.YH_Box.setMinimumSize(QtCore.QSize(0, 40))
        self.YH_Box.setObjectName("YH_Box")
        self.YH_Box.addItem("")
        self.YH_Box.addItem("")
        self.YH_Box.addItem("")
        self.horizontalLayout_2.addWidget(self.YH_Box)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.spinBox_px = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_px.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.spinBox_px.setFont(font)
        self.spinBox_px.setObjectName("spinBox_px")
        self.horizontalLayout_2.addWidget(self.spinBox_px)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spit_Box = QtWidgets.QComboBox(self.widget_3)
        self.spit_Box.setMinimumSize(QtCore.QSize(0, 40))
        self.spit_Box.setObjectName("spit_Box")
        self.spit_Box.addItem("")
        self.spit_Box.addItem("")
        self.spit_Box.addItem("")
        self.horizontalLayout_2.addWidget(self.spit_Box)
        self.cleanTemp = QtWidgets.QPushButton(self.widget_3)
        self.cleanTemp.setMinimumSize(QtCore.QSize(0, 40))
        self.cleanTemp.setObjectName("cleanTemp")
        self.horizontalLayout_2.addWidget(self.cleanTemp)
        self.withdraw = QtWidgets.QPushButton(self.widget_3)
        self.withdraw.setMinimumSize(QtCore.QSize(0, 40))
        self.withdraw.setObjectName("withdraw")
        self.horizontalLayout_2.addWidget(self.withdraw)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(5, 1)
        self.horizontalLayout_2.setStretch(6, 1)
        self.horizontalLayout_2.setStretch(7, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.BinProcess = QtWidgets.QCheckBox(self.widget_4)
        self.BinProcess.setObjectName("BinProcess")
        self.verticalLayout_5.addWidget(self.BinProcess)
        self.AutoED = QtWidgets.QCheckBox(self.widget_4)
        self.AutoED.setObjectName("AutoED")
        self.verticalLayout_5.addWidget(self.AutoED)
        self.StudyPreView = QtWidgets.QCheckBox(self.widget_4)
        self.StudyPreView.setObjectName("StudyPreView")
        self.verticalLayout_5.addWidget(self.StudyPreView)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.widget_4)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked['bool'].connect(MainWindow.button_spit_num)
        self.pushButton_3.clicked['bool'].connect(MainWindow.button_clear)
        self.pushButton_2.clicked['bool'].connect(MainWindow.button_recognize)
        self.withdraw.clicked['bool'].connect(MainWindow.button_withdraw)
        self.cleanTemp.clicked['bool'].connect(MainWindow.button_clear_alltemp)
        self.pushButton_4.clicked['bool'].connect(MainWindow.button_preView)
        self.spinBox_px.valueChanged['int'].connect(MainWindow.spin_num_change)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.YH_Box.setItemText(0, _translate("MainWindow", "腐蚀膨胀"))
        self.YH_Box.setItemText(1, _translate("MainWindow", "腐蚀"))
        self.YH_Box.setItemText(2, _translate("MainWindow", "膨胀"))
        self.pushButton_4.setText(_translate("MainWindow", "执行操作并预览"))
        self.label_2.setText(_translate("MainWindow", "px"))
        self.spit_Box.setItemText(0, _translate("MainWindow", "简单分割"))
        self.spit_Box.setItemText(1, _translate("MainWindow", "认真分割-BFS"))
        self.spit_Box.setItemText(2, _translate("MainWindow", "认真分割-DFS"))
        self.cleanTemp.setText(_translate("MainWindow", "清除所有效果"))
        self.withdraw.setText(_translate("MainWindow", "撤回"))
        self.pushButton_3.setText(_translate("MainWindow", "清除画板"))
        self.pushButton.setText(_translate("MainWindow", "分割数字"))
        self.pushButton_2.setText(_translate("MainWindow", "识别数字"))
        self.BinProcess.setText(_translate("MainWindow", "二值化阀值处理"))
        self.AutoED.setText(_translate("MainWindow", "自动膨胀腐蚀"))
        self.StudyPreView.setText(_translate("MainWindow", "图片预览"))
        self.label.setText(_translate("MainWindow", "数字显示："))

